### ISSUE TITLE
Better README.md

### ISSUE THREAD

**Issue by MikeRaphK** [MikeRaphK/PAUL#3]
Hey PAUL! Can you write a better README.md file? Here is what I want:
- An analytical setup for cloning, installing dependencies and building/running the docker container locally.
- An analytical setup for adding it as a GitHub action in another repository. This is the run-paul.yml file that gets the job done:
```yml
name: Run PAUL

on:
  # Workflow can be triggered with a click of a button. User inputs issue number.
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue Number"
        required: true
  # Workflow is triggered automatically when an issue is opened/reopened
  issues:
    types: [opened, reopened]

jobs:
  run-paul:
    runs-on: ubuntu-latest
    steps:
      - name: Run PAUL
        uses: MikeRaphK/PAUL@main
        with:
          repo_url: https://github.com/${{ github.repository }}
          issue_number: ${{ github.event.issue.number || github.event.inputs.issue_number }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.PAUL_GITHUB_TOKEN }}
```
- A usage guide
- A section showcasing the mermaid chart of PAUL:
```mermaid
flowchart LR
    A[Get Open Issues] --> B[Clone Repo Locally];
    B --> C[Create PAUL-branch];
    C --> D[Build ReAct Graph];
    D --> P((Ask PAUL for a patch));
    P -. Need a tool? -.-> T(Toolkit);
    P -. Done patching? -.-> E[Create Pull Request];
    T -->|Here's a tool call| P
```
- Any other useful sections you might deem necessary
